#!/usr/bin/env python3
"""
Regenerate src/wizard/rig.ts from public/logo.png.

The logo silhouette is cut into parts at its joints (shoulder, wrist, neck, waist,
broom binding) and each part is traced to an SVG path. Moving parts reach a few
pixels into the body so a rotated joint never opens a gap.

    pip install potracer pillow numpy
    python scripts/trace_wizard.py
"""

import json
from pathlib import Path

import numpy as np
import potrace
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "public" / "logo.png"
OUT = ROOT / "src" / "wizard" / "rig.ts"

VIEWBOX = "170 170 700 700"
TIP = [246, 249]  # wand tip

# polygon (source pixels), pivot (joint), overlap (px reaching into the body)
HAND = {"poly": [(222, 222), (349, 300), (349, 362), (222, 362)], "pivot": [348, 336], "overlap": 8}
PARTS = {
    "wandArm": {"poly": [(225, 225), (300, 285), (400, 322), (512, 336), (514, 414), (420, 422), (320, 404), (225, 335)], "pivot": [506, 378]},
    "head": {"poly": [(415, 180), (705, 180), (705, 300), (655, 328), (612, 342), (560, 338), (514, 336), (415, 322)], "pivot": [598, 338]},
    "cape": {"poly": [(175, 445), (465, 412), (516, 416), (518, 560), (474, 652), (175, 652)], "pivot": [512, 470], "overlap": 26},
    "bristles": {"poly": [(175, 656), (442, 656), (468, 700), (446, 760), (175, 870)], "pivot": [452, 704]},
}
OVERLAP = 14
ORDER = ["cape", "bristles", "body", "head", "wandArm", "hand"]  # back to front

rgba = np.array(Image.open(SRC).convert("RGBA"))
W, H = rgba.shape[1], rgba.shape[0]
ink = (np.array(Image.open(SRC).convert("L")) < 128) & (rgba[..., 3] >= 128)


def poly_mask(poly, grow=0):
    m = Image.new("L", (W, H), 0)
    ImageDraw.Draw(m).polygon(poly, fill=255)
    if grow:
        m = m.filter(ImageFilter.MaxFilter(grow * 2 + 1))
    return np.array(m) > 0


def num(v):
    s = f"{v:.1f}"
    return s[:-2] if s.endswith(".0") else s


def to_d(mask):
    # potracer traces the False pixels, so pass the inverse
    path = potrace.Bitmap(~mask).trace(turdsize=6, alphamax=1.0, opticurve=True, opttolerance=0.2)
    out = []
    for c in path:
        out.append(f"M{num(c.start_point.x)} {num(c.start_point.y)}")
        for s in c.segments:
            if s.is_corner:
                out.append(f"L{num(s.c.x)} {num(s.c.y)}L{num(s.end_point.x)} {num(s.end_point.y)}")
            else:
                out.append(f"C{num(s.c1.x)} {num(s.c1.y)} {num(s.c2.x)} {num(s.c2.y)} {num(s.end_point.x)} {num(s.end_point.y)}")
        out.append("Z")
    return "".join(out)


hand_core = poly_mask(HAND["poly"]) & ink
result = {"hand": {"d": to_d(poly_mask(HAND["poly"], HAND["overlap"]) & ink), "pivot": HAND["pivot"]}}
claimed = hand_core.copy()
for name, p in PARTS.items():
    core = poly_mask(p["poly"]) & ink
    reach = poly_mask(p["poly"], p.get("overlap", OVERLAP)) & ink
    if name == "wandArm":
        reach &= ~hand_core
    claimed |= core
    result[name] = {"d": to_d(reach), "pivot": p["pivot"]}
result["body"] = {"d": to_d(ink & ~claimed), "pivot": [590, 560]}

lines = [
    "// Generated by scripts/trace_wizard.py from public/logo.png. Do not edit by hand.",
    "// Each part is the logo silhouette cut at a joint; pivot is the joint it rotates around (source pixels).",
    "",
    "export type WizardPart = " + " | ".join(f'"{k}"' for k in ORDER) + ";",
    "",
    f'export const WIZARD_VIEWBOX = "{VIEWBOX}";',
    "/** Wand tip, in source pixels. Sparkles are emitted from here. */",
    f"export const WIZARD_TIP: [number, number] = {json.dumps(TIP)};",
    "",
    "export const WIZARD_PARTS: Record<WizardPart, { d: string; pivot: [number, number] }> = {",
]
for k in ORDER:
    lines.append(f"  {k}: {{ pivot: {json.dumps(result[k]['pivot'])}, d: {json.dumps(result[k]['d'])} }},")
lines.append("};")
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")
